### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by AndreyKrutienko74** [oleksandrblazhko/ai204-krutienko#10]
1. Потреба: Сон
Зрозумілість: не буде мати важких умов та визначень, що можуть бути незрозумілими користвачу даних сну.
Доступність: дані про сон будenm доступні кожному та можуть бути використані у будь-який час.
Цінність: для того, щоб отримати сон, не треба буде витрачати кошти.
2.
Перший прецедент дає можливість переглядати базу даних та змінювати додаткові деталі, що призводить до наближення до мети, що пов'язана з перегляданням даних

Другий прецедент дає можливість зареєструватися, тим самим наближає користувача до мети, що пов’язана з оплатою штрафу

Третій прецедент має можливість отримувати дані про водія, що наближує до мети з надсилання повідомлення про штраф.

Четвертий прецедент має можливість додавати дані про водія та його порушення, що наближує до мети з оновлення даних та їх обробку

**Comment by oleksandrblazhko** [comment]
Оцінка = 3 бали
