### ISSUE TITLE
CW2

### ISSUE THREAD

**Issue by AndreyKrutienko74** [oleksandrblazhko/ai204-krutienko#13]
Завдання 1
Атомарність - водій отримає повідомлення про штраф та сплачує штраф
Завершеність - поліцейський виконує свою роботу 
Безкоштовність реалізації - поліцейський друкує штраф

Завдання 2
1- Показники технічної складності проекту TCF "Розподілена система" - значення 3, було обрано через навантаженність програмного продукту. Продукт має середній рівень функціоналу.
2- Показники технічної складності проекту TCF "Спеціальні вимоги до навчання користувачів" - значення 1, було обрано через те, що не потрібно мати особливих навичок, щоб користуватись ПП. Інтерфейс простий та інтуітивно зрозумілий

**Comment by oleksandrblazhko** [comment]
Оцінка = 3 бали
